- hosts: jenkinsVMM
  remote_user: root
  tasks:
    - name: Clean inventory path
      file:
        state: absent
        path: "/var/lib/jenkins/workspace/inventory/*"
    - name: TODO
      copy:
        src: "{{ inventory_dir }}/"
        dest: /var/lib/jenkins/workspace/inventory/
        owner: jenkins
        group: jenkins
