sysname: CometariRouter
initial_ip_address: 10.69.181.31
external_ip_address: 10.69.181.2
external_subnetmask: 255.255.252.0
default_gateway: 10.69.180.1
internal_ip_address: 10.69.182.97
dhcp_pool_name: cometariPool
dhcp_network: 10.69.182.96
dns_by_dhcp: 10.69.177.253
username: hp 
password: hp123
force_stop: True
